# CONFIGURATION FILE
# example config file - rename it to config.yaml and set up your values for ftp connection
ftp_server_credentials:
    server: your-host
    login: your-username
    password: your-password
    subfolder: /

html_config:
    report_name: online-report
    ftp_upload: False
    subfolder: /
